#!/usr/bin/env python3
"""Speed comparison report for psychicstd across every real-world project in
use_on_realworld_projects/, generated systematically instead of by hand.

For each project, builds it on THIS machine -- once with system libstdc++,
once with the working tree's psychicstd headers -- under debug and release,
and reports one step/system/psychicstd/speedup table per project per build
type, colored and with a bootstrapped 95% confidence interval on the speedup
ratio. This is the same shape as the use_on_realworld_projects/*_speed_report.md
files that used to be regenerated by hand, one project at a time, but for
every project at once. Unlike compare_realworld.py (which diffs a git ref
against the working tree to catch a PR's regressions), this reports the
working tree's absolute speedup over system libstdc++.

Usage:
  scripts/compare_realworld_performance.py [--compiler CXX]
      [--build-type {debug,release,both}] [--reps N]
      [--project {NAME,all} ...] [--enable-ccache] [--output PATH]
      [--jobs N] [--check-only]
  scripts/compare_realworld_performance.py --list
"""

import argparse
import os
import random
import statistics
import subprocess
import sys
from pathlib import Path


def _git_toplevel() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    )
    return Path(out.stdout.strip())


REPO = _git_toplevel()
for _sub in ("use_on_realworld_projects", "scripts"):
    sys.path.insert(0, str(REPO / _sub))
import realworld_projects as rw  # noqa: E402
import compare_realworld as cr  # noqa: E402

GREEN, RED, YELLOW = "\U0001f7e2", "\U0001f534", "\U0001f7e1"
BUILD_TYPE_CHOICES = (*cr.BUILD_TYPES, "both")


def bootstrap_speedup_ci(
    sys_samples: list[float],
    psy_samples: list[float],
    iters: int = 2000,
    seed: int = 12345,
) -> tuple[float, float] | None:
    """95% CI for the speedup ratio (system time / psychicstd time), by
    bootstrap resampling. Returns (lo, hi) in the same "x" units as the
    speedup itself, or None when there aren't enough samples to resample."""
    if len(sys_samples) < 2 or len(psy_samples) < 2:
        return None
    rnd = random.Random(seed)
    ns, npy = len(sys_samples), len(psy_samples)
    ratios = []
    for _ in range(iters):
        s = statistics.median(rnd.choice(sys_samples) for _ in range(ns))
        p = statistics.median(rnd.choice(psy_samples) for _ in range(npy))
        if p:
            ratios.append(s / p)
    if not ratios:
        return None
    ratios.sort()
    lo = ratios[int(0.025 * (len(ratios) - 1))]
    hi = ratios[int(0.975 * (len(ratios) - 1))]
    return lo, hi


def _color(ci: tuple[float, float] | None) -> str:
    if ci is None:
        return YELLOW
    lo, hi = ci
    if lo > 1:
        return GREEN  # CI entirely above 1x: reliably faster
    if hi < 1:
        return RED  # CI entirely below 1x: reliably slower
    return YELLOW  # CI straddles 1x (no change)


def _speedup_cell(sys_samples: list[float], psy_samples: list[float]) -> str:
    if not sys_samples or not psy_samples:
        return "—"
    s, p = statistics.median(sys_samples), statistics.median(psy_samples)
    if not s or not p:
        return "—"
    speedup = s / p
    ci = bootstrap_speedup_ci(sys_samples, psy_samples)
    ci_txt = f" [{ci[0]:.2f}x, {ci[1]:.2f}x]" if ci else ""
    return f"{_color(ci)} {speedup:.2f}x{ci_txt}"


def _row(
    step: str, sys_samples: list[float], psy_samples: list[float], comment: str
) -> str:
    if not sys_samples or not psy_samples:
        return f"| {step} | — | — | — | {comment} |"
    s_ms, p_ms = statistics.median(sys_samples), statistics.median(psy_samples)
    return (
        f"| {step} | {s_ms / 1000:.2f} | {p_ms / 1000:.2f} | "
        f"{_speedup_cell(sys_samples, psy_samples)} | {comment} |"
    )


def _table(spec: rw.Project, samples: dict[str, dict[str, list[float]]]) -> list[str]:
    return [
        "| step | system (s) | psychicstd (s) | speedup | comment |",
        "| --- | ---: | ---: | ---: | --- |",
        *(
            _row(
                p,
                samples["system"][p],
                samples["psychicstd"][p],
                spec.comments.get(p, ""),
            )
            for p in spec.phases
        ),
        "",
    ]


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--project",
        dest="projects",
        action="append",
        choices=(*sorted(rw.PROJECTS), "all"),
        help="project to include (repeatable; 'all' for every known project; "
        "default: all)",
    )
    ap.add_argument("--compiler", default="c++", help="C++ compiler (default: c++)")
    ap.add_argument(
        "--build-type",
        choices=BUILD_TYPE_CHOICES,
        default="both",
        help="build type(s) to report, translated per-project (default: both)",
    )
    ap.add_argument(
        "--reps", type=int, default=3, help="build repetitions (default: 3)"
    )
    ap.add_argument(
        "--jobs",
        type=int,
        help="parallel build jobs (default: automatically detected)",
    )
    ap.add_argument(
        "--enable-ccache",
        action="store_true",
        help="leave ccache enabled (faster iteration, but skews timings -- use "
        "for debugging the script/recipes, not for real measurements)",
    )
    ap.add_argument(
        "--output",
        type=Path,
        metavar="PATH",
        help="also write the report to this file (in addition to stdout)",
    )
    ap.add_argument(
        "--check-only",
        action="store_true",
        help="only verify that the selected project(s) build under psychicstd; "
        "skip the system-vs-psychicstd timing report",
    )
    ap.add_argument(
        "--list",
        action="store_true",
        help="print known project names, one per line, and exit",
    )
    args = ap.parse_args()

    if args.jobs is not None and args.jobs <= 0:
        ap.error("--jobs must be positive")

    if not args.enable_ccache:
        os.environ["CCACHE_DISABLE"] = "1"

    if args.list:
        print("\n".join(sorted(rw.PROJECTS)))
        return 0

    if not args.projects or "all" in args.projects:
        projects = sorted(rw.PROJECTS)
    else:
        projects = sorted(args.projects)
    build_types = cr.BUILD_TYPES if args.build_type == "both" else (args.build_type,)
    parallelism = rw.detect_parallelism()
    jobs = args.jobs if args.jobs is not None else parallelism.jobs

    if args.check_only:
        if args.output:
            print(
                "--output is ignored with --check-only",
                file=sys.stderr,
            )
        for project in projects:
            for build_type in build_types:
                print(f"Checking {project} ({build_type}) ...", file=sys.stderr)
                cr.check_project(
                    project,
                    args.compiler,
                    build_type,
                    REPO / "include",
                    args.enable_ccache,
                    jobs,
                )
        return 0

    results = {}
    for project in projects:
        for build_type in build_types:
            print(f"Measuring {project} ({build_type}) ...", file=sys.stderr)
            results[project, build_type] = cr.measure_project(
                project,
                args.compiler,
                build_type,
                args.reps,
                REPO / "include",
                args.enable_ccache,
                jobs,
            )

    ver = cr.compiler_version(args.compiler) or "unknown"

    lines = [
        "# Real-world project speed comparison\n",
        f"Compiler: `{ver}`. Each project is built {args.reps} time(s) per side "
        f"(system {'libc++' if sys.platform == 'darwin' else 'libstdc++'}, "
        "psychicstd); `system (s)`/`psychicstd (s)` are the "
        "*median* build time of those repetitions, in seconds -- the median is "
        "used instead of the mean so one repetition disturbed by another process "
        "on the machine doesn't skew the result. `speedup` = system median / "
        "psychicstd median (>1x means psychicstd is faster); its bracketed range "
        "is a 95% confidence interval on that *same ratio* (obtained by "
        "resampling the raw per-repetition timings, not just the two medians, "
        "2000 times) -- so it reflects how much the repetitions varied, not a "
        "different unit. "
        f"{GREEN} the whole CI is above 1x (reliably faster) · {RED} the whole "
        f"CI is below 1x (reliably slower) · {YELLOW} the CI straddles 1x (not "
        "distinguishable from run-to-run noise).\n",
        f"Parallelism: **{jobs} jobs** "
        f"({parallelism.logical_cpus} logical CPUs available; the memory "
        f"estimate permits {parallelism.memory_jobs} jobs at 1.5 GiB/job). "
        f"ccache was {'enabled' if args.enable_ccache else 'disabled'}.\n",
    ]
    if args.enable_ccache:
        lines.append(
            f"{YELLOW} **ccache was left enabled -- these timings are skewed "
            "and not representative of a real build.**\n"
        )
    for project in projects:
        spec = rw.PROJECTS[project]
        lines.append(f"## {project} ({spec.version})\n")
        if spec.comment:
            lines.append(f"{spec.comment}\n")
        for build_type in build_types:
            lines.append(f"### {build_type.title()}\n")
            lines.extend(_table(spec, results[project, build_type]))

    lines.append(
        "---\nReproduce this on your machine: "
        f"`scripts/compare_realworld_performance.py --compiler {args.compiler} "
        f"--build-type {args.build_type} --reps {args.reps} --jobs {jobs}"
        + (" --enable-ccache" if args.enable_ccache else "")
        + "`"
    )

    report = "\n".join(lines)
    print(report)
    if args.output:
        args.output.write_text(report + "\n", encoding="utf-8")
        if subprocess.run(["which", "mdformat"], capture_output=True).returncode == 0:
            subprocess.run(["mdformat", str(args.output)], check=True)
        print(f"Report written to {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
