#!/usr/bin/env python3
"""
Compares two compliance cache files and emits a markdown summary.

Intended for CI: the base cache comes from the main-branch artifact; the head
cache is generated by re-running (--recheck) those exact same tests against the
PR's psychicstd headers.  Because both caches contain the same test files, the
comparison is always on an identical corpus - no intersection logic needed.

Usage:
  python3 tools/compliance_diff.py --base base_cache.json --head head_cache.json
"""

import argparse
import json
from pathlib import Path


def load(path: str) -> dict:
    return json.loads(Path(path).read_text())


def passes(cache: dict, header: str) -> tuple[int, int]:
    """Return (n_pass, n_sampled) for a header from a cache dict."""
    tests: dict = cache.get(header, {}).get("tests", {})
    n_pass = sum(1 for v in tests.values() if v.get("psy") == "pass")
    return n_pass, len(tests)


def delta_emoji(delta: int) -> str:
    if delta > 0:
        return "\N{LARGE GREEN CIRCLE}"  # 🟢
    if delta < 0:
        return "\N{LARGE RED CIRCLE}"  # 🔴
    return "\N{WHITE LARGE SQUARE}"  # ⬜


def main() -> None:
    ap = argparse.ArgumentParser(description="Diff two compliance caches")
    ap.add_argument("--base", required=True, metavar="JSON", help="Base (main) cache")
    ap.add_argument("--head", required=True, metavar="JSON", help="Head (PR) cache")
    ap.add_argument(
        "--title", default="Compliance diff", help="Heading for the markdown table"
    )
    ap.add_argument(
        "--reproduce",
        metavar="CMD",
        help="Append a line telling the reader how to regenerate this diff locally",
    )
    args = ap.parse_args()

    base = load(args.base)
    head = load(args.head)

    all_headers = sorted(set(base) | set(head))

    changed: list[tuple[str, int, int, int, int, int]] = []  # h, bp, bs, ap, as, delta
    unchanged: list[str] = []

    for h in all_headers:
        before_pass, before_n = passes(base, h)
        after_pass, after_n = passes(head, h)
        delta = after_pass - before_pass
        if delta != 0:
            changed.append((h, before_pass, before_n, after_pass, after_n, delta))
        else:
            unchanged.append(h)

    # Sort: regressions first (worst delta), then improvements (best delta last)
    changed.sort(key=lambda r: r[5])

    lines: list[str] = [f"## {args.title}\n"]

    if not changed:
        lines.append("No changes detected.\n")
    else:
        gains = sum(1 for *_, d in changed if d > 0)
        losses = sum(1 for *_, d in changed if d < 0)
        parts = []
        if losses:
            parts.append(f"\N{LARGE RED CIRCLE} {losses} header(s) regressed")
        if gains:
            parts.append(f"\N{LARGE GREEN CIRCLE} {gains} header(s) improved")
        lines.append(", ".join(parts) + ".\n")

        lines.append("| header | before | after | \N{GREEK CAPITAL LETTER DELTA} |")
        lines.append("|--------|--------|-------|---|")
        for h, bp, bs, ap_, as_, delta in changed:
            sign = f"+{delta}" if delta > 0 else str(delta)
            emoji = delta_emoji(delta)
            lines.append(f"| `{h}` | {bp}/{bs} | {ap_}/{as_} | {emoji} {sign} |")
        lines.append("")

    if unchanged:
        lines.append(
            f"<details><summary>{len(unchanged)} header(s) unchanged</summary>\n"
        )
        lines.append("| header | passes/sampled |")
        lines.append("|--------|----------------|")
        for h in unchanged:
            p, n = passes(head, h)
            lines.append(f"| `{h}` | {p}/{n} |")
        lines.append("\n</details>")

    if args.reproduce:
        lines.append(f"\n---\nReproduce this on your machine: `{args.reproduce}`")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
