---
name: build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  BUILD_TYPE: Debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DPSYCHICSTD_BUILD_BENCHMARKS=OFF
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
  ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure CMake (UBSan)
        run: cmake -B ${{github.workspace}}/build_ubsan -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DPSYCHICSTD_BUILD_BENCHMARKS=OFF -DCMAKE_CXX_FLAGS="-fsanitize=undefined
          -fsanitize-trap=undefined" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=undefined"
          -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=undefined"
      - name: Build (UBSan)
        run: cmake --build ${{github.workspace}}/build_ubsan --config ${{env.BUILD_TYPE}}
      - name: Test (UBSan)
        working-directory: ${{github.workspace}}/build_ubsan
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
  asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Configure CMake (ASan)
        run: cmake -B ${{github.workspace}}/build_asan -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DPSYCHICSTD_BUILD_BENCHMARKS=OFF -DCMAKE_CXX_FLAGS="-fsanitize=address"
          -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_SHARED_LINKER_FLAGS="-fsanitize=address"
      - name: Build (ASan)
        run: cmake --build ${{github.workspace}}/build_asan --config ${{env.BUILD_TYPE}}
      - name: Test (ASan)
        working-directory: ${{github.workspace}}/build_asan
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
  gcc12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install GCC 12
        run: sudo apt-get update -qq && sudo apt-get install -y -qq g++-12
      - name: Configure CMake (GCC 12)
        run: >
          cmake -B ${{github.workspace}}/build_gcc12
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DPSYCHICSTD_BUILD_BENCHMARKS=OFF
          -DCMAKE_C_COMPILER=gcc-12
          -DCMAKE_CXX_COMPILER=g++-12
      - name: Build (GCC 12)
        run: cmake --build ${{github.workspace}}/build_gcc12 --config ${{env.BUILD_TYPE}}
      - name: Test (GCC 12)
        working-directory: ${{github.workspace}}/build_gcc12
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
